# Generated by Django 5.2.5 on 2025-08-23 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("boys", "Boys"),
                            ("girls", "Girls"),
                            ("unisex", "Unisex"),
                        ],
                        default="unisex",
                        max_length=10,
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NB", "Newborn"),
                            ("3M", "3 Months"),
                            ("6M", "6 Months"),
                            ("9M", "9 Months"),
                            ("12M", "12 Months"),
                            ("18M", "18 Months"),
                            ("24M", "24 Months"),
                            ("2T", "2T"),
                            ("3T", "3T"),
                            ("4T", "4T"),
                            ("5T", "5T"),
                            ("6", "Age 6"),
                            ("7", "Age 7"),
                            ("8", "Age 8"),
                            ("9", "Age 9"),
                            ("10", "Age 10"),
                            ("12", "Age 12"),
                            ("14", "Age 14"),
                        ],
                        max_length=10,
                    ),
                ),
                ("brand", models.CharField(blank=True, max_length=120)),
                ("image", models.ImageField(upload_to="products/")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="store.category",
                    ),
                ),
            ],
        ),
    ]
