# Generated by Django 5.2.5 on 2025-09-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_contactmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="gender",
            field=models.CharField(
                choices=[("boys", "Boys"), ("girls", "Girls")],
                default="unisex",
                max_length=10,
            ),
        ),
    ]
